#!/bin/sh -e
# Note: the '-e' flag will make the script stop immediately upon error with 
# the error reflected in the environment.  This lets one issue commands like
# "./build sbitx && ./sbitx" to build then run if it built correctly, and not
# run if the build failed.
F=$@
[ -z "$F" ] && {
   echo "usage:   $0 program"
   echo "example: $0 sbitx"
   exit 1
}
WORKING_DIRECTORY=`pwd`
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
date
mkdir -p "./audio"
mkdir -p "./data"
mkdir -p "./web"

if test -f "data/sbitx.db"; then
	echo "database is intact"
else
	echo "database doesn't exist, it will be created"
	cd data
	sqlite3 sbitx.db < create_db.sql
	cd ..
fi

if [ "$F" != "sbitx" ]; then
  echo "compiling $F in $WORKING_DIRECTORY"
else
  VERSION=`grep VER src/sdr_ui.h | awk 'FNR==1{print $4}' | sed -e 's/"//g'`
  echo "compiling $F version $VERSION in $WORKING_DIRECTORY"
fi
gcc -g -o $F \
	 src/vfo.c src/si570.c src/sbitx_sound.c src/fft_filter.c src/sbitx_gtk.c src/sbitx_utils.c \
    src/i2cbb.c src/si5351v2.c src/ini.c src/hamlib.c src/queue.c src/modems.c src/logbook.c \
		src/modem_cw.c src/settings_ui.c src/ntputil.c \
		src/telnet.c src/macros.c src/modem_ft8.c src/remote.c src/mongoose.c src/para_eq.c src/webserver.c src/$F.c  \
		src/ft8_lib/libft8.a  \
	-lwiringPi -lasound -lm -lfftw3 -lfftw3f -pthread -lncurses -lsqlite3 -lnsl -lrt \
	`pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
 
# This addition is used to provide the application the capability to adjust the local system time -W2JON
echo "Brought to you by the sBitx 64 bit project team - W9JES, W2JON, KF7YDU, and N1QM" 
sudo setcap CAP_SYS_TIME+ep /home/pi/sbitx/sbitx
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
